version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:3000"