version: '3'

services:
  nginx:
    image: nginx:latest
    # Ports swapped for reverse proxy
    ports:
      - "8080:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service

  node-service:
    build: .
    # Ports removed for reverse proxy
    environment:
      - "DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_HOST=${DB_HOST}"
    depends_on:
      - db
      
  db:
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_HOST=${MYSQL_HOST}"
    ports:
      - "3306:3306"
    volumes:
      - ../db/init:/docker-entrypoint-initdb.d

